config/routes.rb
Rails.application.routes.draw do
  root 'tvshows#index'
  resources :tvshows

end

app/models/tvshow.rb
class Tvshow < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController
  before_action :set_tvshow, only: [:show, :edit, :update, :destroy]

  # GET /tvshows
  # GET /tvshows.json
  def index
    @tvshows = Tvshow.all
  end

  # GET /tvshows/1
  # GET /tvshows/1.json
  def show
  end

  # GET /tvshows/new
  def new
    @tvshow = Tvshow.new
  end

  # GET /tvshows/1/edit
  def edit
  end

  # POST /tvshows
  # POST /tvshows.json
  def create
    @tvshow = Tvshow.new(tvshow_params)

    respond_to do |format|
      if @tvshow.save
        format.html { redirect_to @tvshow, notice: 'Tvshow was successfully created.' }
        format.json { render :show, status: :created, location: @tvshow }
      else
        format.html { render :new }
        format.json { render json: @tvshow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tvshows/1
  # PATCH/PUT /tvshows/1.json
  def update
    respond_to do |format|
      if @tvshow.update(tvshow_params)
        format.html { redirect_to @tvshow, notice: 'Tvshow was successfully updated.' }
        format.json { render :show, status: :ok, location: @tvshow }
      else
        format.html { render :edit }
        format.json { render json: @tvshow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tvshows/1
  # DELETE /tvshows/1.json
  def destroy
    @tvshow.destroy
    respond_to do |format|
      format.html { redirect_to tvshows_url, notice: 'Tvshow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tvshow
      @tvshow = Tvshow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tvshow_params
      params.require(:tvshow).permit(:titulo, :ano, :season, :episodio, :nota)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tvshows_helper.rb
module TvshowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cadastrar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tvshows/_form.html.erb
<%= form_for(@tvshow) do |f| %>
  <% if @tvshow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tvshow.errors.count, "error") %> prohibited this tvshow from being saved:</h2>

      <ul>
      <% @tvshow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.text_field :ano %>
  </div>
  <div class="field">
    <%= f.label :season %><br>
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :episodio %><br>
    <%= f.text_field :episodio %>
  </div>
  <div class="field">
    <%= f.label :nota %><br>
    <%= f.text_field :nota %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tvshows/edit.html.erb
<h1>Editing Tvshow</h1>

<%= render 'form' %>

<%= link_to 'Show', @tvshow %> |
<%= link_to 'Back', tvshows_path %>

app/views/tvshows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tvshows</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Ano</th>
      <th>Season</th>
      <th>Episodio</th>
      <th>Nota</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tvshows.each do |tvshow| %>
      <tr>
        <td><%= tvshow.titulo %></td>
        <td><%= tvshow.ano %></td>
        <td><%= tvshow.season %></td>
        <td><%= tvshow.episodio %></td>
        <td><%= tvshow.nota %></td>
        <td><%= link_to 'Show', tvshow %></td>
        <td><%= link_to 'Edit', edit_tvshow_path(tvshow) %></td>
        <td><%= link_to 'Destroy', tvshow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tvshow', new_tvshow_path %>

app/views/tvshows/new.html.erb
<h1>New Tvshow</h1>

<%= render 'form' %>

<%= link_to 'Back', tvshows_path %>

app/views/tvshows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @tvshow.titulo %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @tvshow.ano %>
</p>

<p>
  <strong>Season:</strong>
  <%= @tvshow.season %>
</p>

<p>
  <strong>Episodio:</strong>
  <%= @tvshow.episodio %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @tvshow.nota %>
</p>

<%= link_to 'Edit', edit_tvshow_path(@tvshow) %> |
<%= link_to 'Back', tvshows_path %>